### PR TITLE
Add feature tags

### PR DESCRIPTION
**Pull request by marekdano**
This PR is part of solving issue #8.

- Add a new database model `Tags`
- Add an API endpoint `/tags` to get a list of all tags
- Update documentation

### CODE REVIEW

**Comment by marekdano** [comment]
@lukePeavey can I ask you to look at `circleci` why the build failed, please? When I run `npm run lint` and `npm run test` locally on my laptop, there is no error.

**Comment by lukePeavey** [comment]
> can I ask you to look at circleci why the build failed

It's an issue with the CircleCI configuration. Right now, tests always fail when they run on pull requests from a forked repository. 

Just disregard CircleCI tests.for this PR.

I haven't had a chance to review your PR yet. I'll definitely get to by this weekend. 

Thanks!

**Comment by lukePeavey** [comment]
@marekdano This looks great! I ran the tests locally and everything is passing. 

The one thing I'd like to change is the name of the sample data folder. It should be "data/sample" not "data/samples". Would you mind adding one more commit to change that?

Thanks!

**Comment by marekdano** [comment]
> @marekdano This looks great! I ran the tests locally and everything is passing.
> 
> The one thing I'd like to change is the name of the sample data folder. It should be "data/sample" not "data/samples". Would you mind adding one more commit to change that?
> 
> Thanks!

Glad that tests passed 😄. Push the change.

**Comment by lukePeavey** [comment]
Cool, I'll go ahead and merge this! Thanks

**Pull request merged**
