### PR TITLE
feature: search quotes

### PR DESCRIPTION
**Pull request by mitramejia**
### Summary

- Adds `.envrc` and `./idea`to `.gitignore`
- Adds a `searchQuotes` controller. Url example: `http://localhost:4001/search/love?limit=3&skip=2` 
- Should resolve to 3 quotes whose `content` includes `love`
- Uses the same regex as `listQuotes` controller

Some improvements that can be made:

- order results by relevance
- include authors and tags in the resultset

### CODE REVIEW

**Comment by lukePeavey** [comment]
Thanks for submitting a PR! I definitely like the idea of adding a search endpoint. I'll take a look at this tonight.

**Comment by lukePeavey** [comment]
In terms of the API for this feature, I'd like to make a few small changes...  
Ultimately, my plan is to have two search endpoints, one for authors and one for quotes. So was thinking each one would have a separate endpoint:

- `/search/quotes`
- `/search/authors`

Also, I'd prefer to have the search input be a query param instead of a path param. 

```HTTP
GET /search/quotes/?query=love
```

### Implementation

Another possibility would be to use [text search](https://docs.mongodb.com/manual/text-search/).  This would support some of the additional features you mentioned:

* Search multiple fields (ie `content`, `author`,`tags`)
* Sort search results by score


```js
const { query: searchString } = req.query
let { limit, skip = 0 } = req.query
// Searches all fields that have a text index (@see src/models/Quote.js)
const filter = { $text: { $search: searchString } }
// The `score` field is used to sort results by relevance
// TODO: The `score` field should not be included in the API response.
const projection = { score: { $meta: 'textScore' } }

limit = clamp(parseInt(limit), 1, 50) || 20
skip = parseInt(skip) || 0

const [results, totalCount] = await Promise.all([
  Quotes.find(filter, projection)
    .sort({ score: { $meta: 'textScore' } })
    .limit(limit)
    .skip(skip)
    .select('-__v -authorId'),
    
  Quotes.countDocuments(filter),
])
```

There is already a [text index](https://docs.mongodb.com/manual/core/index-text/#index-feature-text) on the `content` and `author` fields. If we wanted the search to include `tags` as well, we could update that. 


Let me know what you think!

**Comment by lukePeavey** [comment]
I just opened an issue for this as well (#31)

**Comment by mitramejia** [comment]
Thanks for getting back to this. Agreed on all points. [text search](https://docs.mongodb.com/manual/text-search/) looks neat. I'll try to find the bandwidth to work on this, looking forward to it.

**Comment by lukePeavey** [comment]
OK sounds good!

**Comment by lukePeavey** [comment]
@mitramejia If you OK with you, I'm going to make a couple of small changes and then merge this.

**Comment by mitramejia** [comment]
@lukePeavey go for it 👍

**Comment by homerjam** [comment]
👀  This is just what I need, is it documented?

Usage like this?

```http
GET /search/quotes/?query=love
```

Thanks all for the work, great project!

**Comment by lukePeavey** [comment]
@homerjam The search API is not included in the docs yet since its still a work in progress. However, it should be fine to start using this now. 

Yes, thats the correct usage: 

Currently, it takes a single search parameter (`query`) and searches quotes by `content` and `author`. The results are sorted based on text matching score. 

### Examples

**Search by keyword** ([try in browser](https://api.quotable.io/search/quotes/?query=love))
```HTTP
GET /search/quotes/?query=love
```` 

**Search for a quote or phrase** ([try in browser](https://api.quotable.io/search/quotes/?query=a+house+divided))
```HTTP
GET /search/quotes/?query=a house divided
```` 

**Search for quotes by author name** ([try in browser](https://api.quotable.io/search/quotes/?query=Lincoln))
```HTTP
GET /search/quotes/?query=Lincoln
````

**Pull request merged**
