### PR TITLE
Feature: filter quotes by length

### PR DESCRIPTION
**Pull request by Dragonsight91**
After looking into the code and learning some of the MongoDB stuff, it turned out to be a lot simpler than i thought in my issue. 
The only thing needed was a filter on `length` with the standard `$lte` and `$gte`properties set to their appropriate value in both `randomQuote.js` and `listQuotes.js`

After also remembering that unit testing exists, i added the length attribute properly to the response object as well as the unit test.

---

Added `minlength` and `maxlength` query parameters to the following endpoints

- `/quotes`
- `/random`

Reference #19

### CODE REVIEW

**Comment by lukePeavey** [comment]
Sorry about the merge conflicts. PR #22 had been open for a while so wanted to merge that one first. Thanks for resolving them :)

**Comment by Dragonsight91** [comment]
No problem, should all be resolved now

**Comment by Dragonsight91** [comment]
Just noticed i was missing a bit of code, I'll correct it now.

**Comment by Dragonsight91** [comment]
Should be all good to go now

**Comment by Dragonsight91** [comment]
That's the Final change from my side, unless requested otherwise.

**Comment by Dragonsight91** [comment]
Makes sense, changes have been made.

**Comment by lukePeavey** [comment]
🚀I just deployed your changes... should be live now.

**Pull request merged**
