### PR TITLE
enhancement: improve pagination API

### LINKED ISSUE #70: Improve pagination API
## Summary 

Add support for page number based pagination. This approach is simpler and more intuitive. It also requires less code on the client side to implement common pagination patterns. 

This feature can be added on top of the current API without any breaking changes. 

### Example

Get the second page of results, with 50 results per page. 

```HTTP
GET /quotes?page=2&limit=50
```

### New Parameters

Add a `page` parameter to all paginated endpoints. This parameter can be used to specify the page of results to return.  The `limit` param determines the number of results per page. 

### Paginated Response

We can add the following properties to all paginated responses. We do not need to remove or modify any existing properties on the response. 

- `page` the current page of results 
- `totalPages` total number of pages based on results per page

### Implementation

When the `skip` parameter is provided to a paginated endpoint, the `page` param will be ignored. Otherwise, the value of `skip` will calculated from `page` and `limit` (results per page).  This way the current pagination API will still be supported. 

```js
const skip = skipParam || (page - 1) * limit
```

### LINKED ISSUE #71: [Documentation] Incorrect install command in CONTRIBUTING.md
The install dependency command says
```sh
npm run install
```
While it should be
```sh
npm install
```

### PR DESCRIPTION
**Pull request by raxraj**
## Summary 

Improve pagination API by adding support for page number based pagination.  The old pagination system (`skip`/`limit`) will still be supported. 

### Pagination Params

- `page` The page number of results to return.
- `limit` Number of results per page. 

### Paginated Response

Adds two new properties to all paginated responses. 

- `page` the current page of results
- `totalPages` the total number of pages (based on total count and results per page)

###  Example

Get the second page of results, with 50 results per page.

```HTTP
GET /quotes?page=2&limit=50
```

### List of changes

- CONTRIBUTING.md :  #71 , npm install doc fix.
- listQuotes.js and listAuthors.js : #70 To implement the changes and improvements
- list.quotes.test.js and list.quotes.test.js: #70 Adding required test for the changes
- README.md: #70 Documenting the changes made to the pagination API
- ~package.json: "SECURITY VULNERABILITY" mongoose Depends on vulnerable versions of mquery. (mongoose 3.7.0 -> 5.11.6) (NO BREAKING CHANGES INVOLVED) (ALL TEST CASES PASSED)~

I love working on this API.

Closes #70 
Closes #71

### CODE REVIEW

**Comment by lukePeavey** [comment]
Thanks for working on this!

Not sure why all the tests are failing. It looks like CircleCI is failing to connect to MongoDB.  I'll take a look at that today

**Comment by raxraj** [comment]
@lukePeavey , Yes I was looking at it, and was wondering the same, I think the vulnerability fix has something to do with it.
I hope you find the issue, cause it worked pretty find with my atlas mongodb cluster.

And I love to work on this project.

**Comment by lukePeavey** [comment]
I'm glad you enjoy working on the API! I definitely appreciate all your help. 

I'm pretty sure this issue is unrelated to your PR. It seams to be a problem with my Atlas cluster.

**Comment by lukePeavey** [comment]
The tests are passing for me locally using the same `MONGODB_URI` that circle CI uses. So I'm not sure whats causing this. 

It's possible it has something to do with the changes to `package-lock.json`.  Just to rule that out, you could try restoring `package-lock.json` to its current version.  We can fix that vulnerability in a separate PR.  If that does not help, I'll keep looking into it on my end.

**Comment by lukePeavey** [comment]
> It's possible it has something to do with the changes to package-lock.json

I tried rolling back the changes to `package-lock.json`, tests still failing. It must be an issue with CircleCI. I'll keep working on it.

**Comment by lukePeavey** [comment]
I figured it out.  CircleCI uses an Atlas cluster for tests now, so I needed to enable "Pass secrets to builds from forked pull requests" for the tests to work on PRs.

**Comment by raxraj** [comment]
@lukePeavey 
Awesome man, 
Sorry for my unavailability in the mean time.
So hoping you fix that and then we are good to go. :)

**Comment by raxraj** [comment]
@lukePeavey
Now that the tests are passing, but let's keep in mind that the vulnerability fix was rolled back.
We still have that to fix anytime sooner.

**Comment by lukePeavey** [comment]
@raxraj if you want you can add another commit to this PR before I merge it, or submit a separate PR to fix the vulnerability. 

Otherwise I'll fix it later.

**Comment by raxraj** [comment]
@lukePeavey 
I'll make a separate PR.
Go ahead with merging this.

**Comment by lukePeavey** [comment]
Sounds good!

**Comment by lukePeavey** [comment]
Done. Nice work

**Comment by raxraj** [comment]
Awesome :)

**Pull request merged**
