### PR TITLE
fix: change maximum results per page to 150

### LINKED ISSUE #49: List Quotes: Max query is wrong in documentation
In the documentation you have `Max: 100`
image

But  if we set `https://api.quotable.io/quotes?limit=100` (or any number above 50, the count will always be 50.

image

Can the limit be 100 or even the `totalCount` ?

### PR DESCRIPTION
**Pull request by dippas**
Closes #49 

- Increase the maximum value of the `limit` parameter to `150` for the `/quotes` and `/authors` endpoint.  
- Update docs

### CODE REVIEW

**Comment by lukePeavey** [comment]
Thanks for submitting a PR. The changes to the controllers and relevant docs look good. 

As for the other changes to the README...

#### Removing Inline HTML 

I think inline HTML is fine in Github Markdown if it improves the quality of the rendered document. I would rather not remove the `<br>` tags from the **Query Parameters** table. I just think it looks better having the description on a separate line from the `default`, `min`, `max` etc. 

quotable-parameters-table


#### Duplicate sub-headings

Since we are not using the level-4 headings as links, I think its OK to have the same sub-headings under each endpoint.  So I would rather not prefix all the sub-headings with the endpoint name, at least for now. 

```md
### Endpont Name

#### path

#### Query Parameters

#### Response 

#### Examples
```

The rest of the changes to the README are fine.

**Comment by dippas** [comment]
@lukePeavey  thanks for the feedback, I've made a mistake of deleting the fork before PR being accepted, so I tried to fork the repo and update only the README file, but it desn't show here in this thread, however you can check the comparisions from your repo with my fork [here](https://github.com/lukePeavey/quotable/compare/master...dippas:limitQuota) and the commit made it was [this](https://github.com/lukePeavey/quotable/commit/1e1f8eedf388ae9d433fcf36c0839ca2a32d7f59)

**Comment by lukePeavey** [comment]
Ok, no problem! I'm going to go ahead and merge this as is. I have a few other things I need to add to the docs anyway, so I make the changes to the README after I merge it. 

Appreciate the contribution. I'll keep you posted on the images feature 😄

**Comment by dippas** [comment]
@lukePeavey  great! Thanks ;)

**Comment by lukePeavey** [comment]
@dippas this change as been deployed as is now live.

**Pull request merged**
