### PR TITLE
feature: filter random quote by author slug

### PR DESCRIPTION
**Pull request by jcsawyer123**
One file changed:
M: /src/controllers/quotes/randomQuote.js

Allows you to make a query from a random quote using the author slug as opposed to the author's ID or full name.

### CODE REVIEW

**Comment by lukePeavey** [comment]
First, thanks for submitting a PR!

**Comment by lukePeavey** [comment]
So just clarify, the goal is to be able to filter random quotes by author, using the author `slug` field (as oppose to the author `name` or `_id`). 

Example

Get a random quote by A. A. Milne

```HTTP
GET /random?authorSlug=a-a-milne
```

I think this is a great idea! Ultimately I am planning to add an `authorSlug` field to quotes which will be included in the API response. This will make it easier to get details about an author from a quote or vice versa.  

Once we add the `authorSlug` field,  it will be possible to filter by slug without first querying the author. But I'm fine with merging this now and then making that change later. 

Have you already tested this locally to make sure it works?

**Comment by jcsawyer123** [comment]
Yeah, that is the idea!

It works locally as shown in the below screenshot 
image

**Comment by lukePeavey** [comment]
Changes have been deployed 🚀 Thanks for the contribution. I will update the docs later.

**Pull request merged**
