### PR TITLE
feature: get random quote by author

### LINKED ISSUE #40: [Feature Request] Random quote by specific author
I wonder if there is a way to get quotes just from one or several selected authors?
like
`GET /random?authorid=zgMVt2guVo7p,qsaptKSHuLDU`
or
`GET /random?author="Zig Ziglar","Laozi"`

### PR DESCRIPTION
**Pull request by raxraj**
Closes #40

3 Files have been changes. 
- quotable/src/controllers/quotes/randomQuote.js, for adding the functionality to the randomQuote controller.
- __test__/integration.test.js, for adding the test for the feature added (i.e. random quotes from the selected authors).
- README.md, for adding the documentation for the feature added.

### CODE REVIEW

**Comment by lukePeavey** [comment]
Thanks for taking care of this. Your PR looks great! I'm going to merge this.

**Comment by raxraj** [comment]
It is nice to work on something that I use a lot.
On top of that, what a beautiful codebase :)

**Comment by lukePeavey** [comment]
Thanks I'm really glad you like the project.

**Comment by lukePeavey** [comment]
The PR looks perfect, thanks for including the docs and tests

**Comment by lukePeavey** [comment]
I just deployed the latest changes to the production server, so this is live now. Thanks again!

**Comment by raxraj** [comment]
I was looking at it yesterday, I saw them on staging, now that they are Live. Awesome !!
Thanks man!

**Pull request merged**
