### PR TITLE
feature: get author by slug

### PR DESCRIPTION
**Pull request by jcsawyer123**
Adds a new endpoint to get a single author by `slug`.  This is equivalent to the  existing `/author/:id` endpoint except it uses the `slug` field to identify the author. 

### Path

```HTTP
GET /author/slug/:slug
```

### Response

The response is a single `Author` object. It includes the author details and the full list of quotes by the author. 

```ts
{
  // A unique id for this author
  _id: string
  // The author slug 
  slug: string
  // The authors full name
  name: string
  // The number of quotes by this author
  quoteCount: string
  // An array containing all quotes by this author (not paginated)
  quotes: Array<{
    _id: string
    // The quotation text
    content: string
    // The full name of the author
    author: string
    // An array of tag names for this quote
    tags: string[]
    // The length of quote (number of characters)
    length: number
  }>
}
```

### CODE REVIEW

**Comment by lukePeavey** [comment]
Thanks, I'll take a look at this today

**Comment by lukePeavey** [comment]
This looks great!.  We have been discussing adding an endpoint to get author by slug. This is exactly what I had in mind.

**Comment by jcsawyer123** [comment]
What a happy coincidence! I did not look at the issues beforehand as I was just throwing it together for myself!

**Comment by lukePeavey** [comment]
Hope you mind, I edited your PR description a bit. I am going to merge this.  As long as everything works on my end I will deploy it to the production server tonight.

**Comment by lukePeavey** [comment]
Changes have been deployed 🚀

**Pull request merged**
